package de.rki.coronawarnapp.covidcertificate.common.exception

import de.rki.coronawarnapp.R

const val ERROR_MESSAGE_GENERIC = R.string.errors_generic_text_unknown_error_cause
const val ERROR_MESSAGE_TRY_AGAIN = R.string.error_tc_try_again
const val ERROR_MESSAGE_DCC_NOT_SUPPORTED_BY_LAB = R.string.error_tc_dcc_not_supported_by_lab
const val ERROR_MESSAGE_NO_NETWORK = R.string.error_tc_no_network
const val ERROR_MESSAGE_E2E_ERROR_CALL_HOTLINE = R.string.error_tc_e2e_error_call_hotline
const val ERROR_MESSAGE_TRY_AGAIN_DCC_NOT_AVAILABLE_YET = R.string.error_tc_try_again_dcc_not_available_yet
const val ERROR_MESSAGE_CLIENT_ERROR_CALL_HOTLINE = R.string.error_tc_client_error_call_hotline
const val ERROR_MESSAGE_DCC_EXPIRED = R.string.error_tc_dcc_expired
const val ERROR_MESSAGE_CERTIFICATE_LOST_SORRY = R.string.test_certificate_error_409_recovery_description
